<!DOCTYPE html>
<html lang="en-us">
<head>
    <title>Goodreads 👍📚 Part 2: rvesting descriptions &middot; Ángela Castillo-Gill</title>
    <meta name="generator" content="Hugo 0.53" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Ángela Castillo-Gill">
    
      <meta name="description" content="Scraping descriptions with rvest, and starting to explore my read-book descriptions with the tidytext package.">
    
    
    <link rel="canonical" href="../../../2017/10/goodreads-part-2/"/>
    <link rel="icon" href="../../../favicon.ico">
    <link rel="apple-touch-icon" href="../../../apple-touch-icon.png"/>
    <link rel="stylesheet" href="../../../css/style.css">
    <link rel="stylesheet" href="../../../css/font-awesome.min.css">
    <link rel="stylesheet" href="../../../css/monokai.css">
    <link rel="stylesheet" href="../../../css/coarse.css" type="text/css" charset="utf-8">
    <link rel="stylesheet" href="../../../fancybox/jquery.fancybox.css">
    
    <link rel="stylesheet" href="../../../css/tomorrow-night-bright.css">
    
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Source+Code+Pro:regular,medium,bold' rel='stylesheet' type='text/css'>
    <meta property="og:title" content="Goodreads 👍📚 Part 2: rvesting descriptions" />
<meta property="og:description" content="Scraping descriptions with rvest, and starting to explore my read-book descriptions with the tidytext package." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/2017/10/goodreads-part-2/" />
<meta property="og:image" content="/banners/mara_shelves_goodreads_genres.png" />
<meta property="article:published_time" content="2017-10-17T00:00:00&#43;00:00"/>
<meta property="article:modified_time" content="2017-10-17T00:00:00&#43;00:00"/>

    
    
<meta itemprop="name" content="Goodreads 👍📚 Part 2: rvesting descriptions">
<meta itemprop="description" content="Scraping descriptions with rvest, and starting to explore my read-book descriptions with the tidytext package.">


<meta itemprop="datePublished" content="2017-10-17T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2017-10-17T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="1842">

  <meta itemprop="image" content="/banners/mara_shelves_goodreads_genres.png">



<meta itemprop="keywords" content="R,rvest,tidytext," />

    <meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="/banners/mara_shelves_goodreads_genres.png"/>

<meta name="twitter:title" content="Goodreads 👍📚 Part 2: rvesting descriptions"/>
<meta name="twitter:description" content="Scraping descriptions with rvest, and starting to explore my read-book descriptions with the tidytext package."/>
<meta name="twitter:site" content="@acastillogill"/>

    
<link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Alegreya|Source+Sans+Pro" rel="stylesheet">


    

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>
<div class="container">


<div id="container">
	<header id="header">
  <div id="header-main" class="header-inner">
    <div class="outer">
      <a href="../../../" id="logo">
          
          <span class="site-title">Ángela Castillo-Gill</span>
      </a>
      <nav id="main-nav">
          
          
          <a class="main-nav-link" href="../../../">Home</a>
          
          
          
          
          
          

          
          <a class="main-nav-link" href="../../../about/">About</a>
          

          
          
          
          
          <a class="main-nav-link" href="../../../tags/posts/">Posts</a>
          
          
          
          <a class="main-nav-link" href="../../../tags/notes/">Notes</a>
          
          
      </nav>
        <nav id="sub-nav">
          <div class="profile" id="profile-nav">
            <a id="profile-anchor" href="javascript:;"><img class="avatar" src="../../../img/angela.jpeg"><i class="fas fa-caret-down"></i></a>
          </div>
        </nav>
        <div id="search-form-wrap">
          <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form">
              <input type="search" name="q" class="search-form-input" placeholder="Search">
              <button type="submit" class="search-form-submit">
              </button>
              <input type="hidden" name="sitesearch" value="/" />
         </form>
        </div>
    </div>
  </div>
  <div id="main-nav-mobile" class="header-sub header-inner">
    <table class="menu outer">
      <tbody>
          <tr>
          
          
          <td><a class="main-nav-link" href="../../../">Home</a></td>
          
          
          
          
          
          

          
          <td><a class="main-nav-link" href="../../../about/">About</a></td>
          

          
          
          
          
          <td><a class="main-nav-link" href="../../../tags/posts/">Posts</a></td>
          
          
          
          <td><a class="main-nav-link" href="../../../tags/notes/">Notes</a></td>
          
          
          <td>
          <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form">
          <input type="search" name="q" class="search-form-input" placeholder="Search">
          <input type="hidden" name="sitesearch" value="/" />
          </form>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</header>

   	
   	<div class="outer">
   	
    	<aside id="profile">
  <div class="inner profile-inner">
    <div class="base-info profile-block">
      
      <img id="avatar" src="../../../img/angela.jpeg">
      
      <h2 id="name">Ángela Castillo-Gill</h2>
      <h3 id="title">Data Analyst training to be a Data Scientist</h3>
      
      
          <a id="follow" href="https://twitter.com/acastillogill">
              @dataandme
          </a>
      
    </div>
    <div class="article-info profile-block">
      <div class="article-info-block">
        36
        <span>Posts</span>
      </div>
      <div class="article-info-block">
        
          29
        
        <span>
            Tags
        </span>
      </div>
    </div>
    <div class="profile-block social-links">
      <table>
        <tr>
          
<td><a href="//github.com/acastillogill" target="_blank" title="GitHub"><i class="fab fa-github-square"></i></a></td>



<td><a href="//twitter.com/acastillogill" target="_blank" title="Twitter"><i class="fab fa-twitter-square"></i></a></td>





























<td><a href="//medium.com/@@acastillogill" target="_blank" title="Medium"><i class="fab fa-medium"></i></a></td>









<td><a href="//linkedin.com/in/acastillogill" target="_blank" title="LinkedIn"><i class="fab fa-linkedin"></i></a></td>















          <td><a href="../../../index.xml" target="_blank" title="RSS"><i class="fas fa-rss-square"></i></a></td>
        </tr>
      </table>
    </div>
  </div>
</aside>

    

    <section id="main">
    
    <article id="page-undefined" class="article article-type-page" itemscope="" itemprop="blogPost">
    <div class="article-inner">
        
            <img src="../../../banners/mara_shelves_goodreads_genres.png" class="article-banner">
        

        <header class="article-header">
    <a href="../../../2017/10/goodreads-part-2/">
    <h1 class="article-title" itemprop="name">
        Goodreads 👍📚 Part 2: rvesting descriptions
    </h1>
    </a>
    <div class="article-meta">

        
        <div class="article-date">
            <i class="far fa-calendar"></i>
            <time datetime="2017-10-17 00:00:00 &#43;0000 UTC" itemprop="datePublished">2017-10-17</time>
            &middot;
            1842
            words
            &middot;
            9
            minute read
        </div>
        
        
            
            
        

        
            
            
            <div class="article-category">
                <i class="fas fa-tags"></i>
                
                
                <a class="article-category-link" href="../../../tags/r">R</a>
                &middot;
                
                
                <a class="article-category-link" href="../../../tags/rvest">rvest</a>
                &middot;
                
                
                <a class="article-category-link" href="../../../tags/tidytext">tidytext</a>
                
                
            </div>
            
        
    </div>
</header>

        <div class="article-entry" itemprop="articleBody">
            


<div id="preamble" class="section level3">
<h3>Preamble</h3>
<p>Much of the code herein has been adapted from the excellent post <a href="http://giorasimchoni.com/2017/09/24/2017-09-24-where-my-girls-at/">“Where my girls at? Scraping Goodreads and using ML to estimate how many children’s books have a cetnral female character”</a> by <a href="https://twitter.com/GioraSimchoni">Giora Simchoni</a>, which I highly recommend.</p>
<p>I’ll also make reference to <a href="https://maraaverick.rbind.io/2017/08/goodreads-part-i-rgoodreads/">my earlier post</a> using my Goodreads data, should you want to check that out.</p>
<div id="why-arent-you-using-the-api" class="section level4">
<h4>😱 Why aren’t you using the API?!</h4>
<p><em>Calm down!</em> Yes, I know there is a perfectly lovely <a href="https://www.goodreads.com/api">Goodreads API</a>– and, by <em>“perfectly lovely”</em> I mean for getting pretty much any data <em>other</em> than book descriptions (which, as you will soon discover, are the objects of my desire).</p>
</div>
</div>
<div id="regular-amble" class="section level2">
<h2>Regular-amble</h2>
<p>When I came upon Giora’s post I experienced that weird sort of non-relief that occurs when you no longer have a good excuse to put off a project you’ve been wanting to do, but have been too lazy to actually execute.</p>
<p>Giora uses a one two punch of the <a href="https://github.com/hadley/rvest"><code>rvest</code></a> and <a href="http://purrr.tidyverse.org/"><code>purrr</code></a> packages to scrape descriptions of children’s books included on a Goodreads list (<a href="https://www.goodreads.com/list/show/226.Favorite_books_from_my_childhood">“Favorite books from my childhood”</a>) and get them into tibbles. This is something I’ve been threatening to do for my own collection of <a href="https://www.goodreads.com/review/list/1923002?shelf=read">read books</a> on Goodreads, so I figured an adaptation wouldn’t be too much trouble.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p>Since lists (the object of Giora’s analysis) and shelves are different (no one votes on whether or not a book should be on my <code>read</code> shelf— I either read it, or I didn’t, so <code>nVoters</code> wouldn’t be a variable for me), I expected there to be a few necessary changes in the code. However, I initially struggled more than I had expected…</p>
<div id="my-rookie-mistake" class="section level3">
<h3>My rookie mistake 😳</h3>
<p>In many (most?) <code>rvest</code> tutorials, you’ll learn about a Chrome bookmarklet called <a href="http://selectorgadget.com/"><strong>SelectorGadget</strong></a> (heck, it even has its own <a href="https://cran.r-project.org/web/packages/rvest/vignettes/selectorgadget.html">eponymous vignette</a> by <a href="https://twitter.com/hadleywickham">Hadley Wickham</a> in the <code>rvest</code> docs). It’s basically a tool that helps you identify the CSS or XPath selectors for finding certain elements of a webpage you’re trying to scrape.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<p>Though I won’t give you a play-by-play of my fruitless attempts, it basically came down to the fact that I was trying to figure things out while <em>logged in</em> to my account.</p>
<p><img src="https://i.imgur.com/Bo6sLIE.png" />
<br /></p>
<p>There <em>are</em> ways to scrape sites with R while logged in.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> However, it turned out that <em>not</em> being logged in was to my advantage as:</p>
<p><strong>1. There’s more data that shows up on the page when you’re not logged in</strong> (see below) and;<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<p><img src="https://i.imgur.com/yHxYZgl.png" />
<br /></p>
<p><strong>2. Pagination actually works the way it’s supposed to</strong> (which means you can get 30 entries at a time, rather than dealing with the annoying infinite-scroll interface over and over).</p>
<p><img src="https://i.imgur.com/toPjFh8.png" />
<br /></p>
</div>
<div id="back-on-course-to-scrape" class="section level3">
<h3>Back on course to scrape 😌</h3>
<p>Once I got my selectorGadget situation sorted, the code was, as expected, easily adaptable. With the <a href="https://www.tidyverse.org/"><code>tidyverse</code></a>, <a href="http://stringr.tidyverse.org/"><code>stringr</code></a>, and <code>rvest</code> packages, I could construct a scraper, and clean some things up. Then, using <code>purrr</code>’s <code>map_dfr</code> bind the rows from each page together into a single data frame (or tibble, rather).</p>
<div id="oh-one-more-thing" class="section level4">
<h4>Oh, one more thing! ☝️</h4>
<p>I also made a bit of a last-minute decision to scrape the <strong>GENRES</strong> from the book pages.</p>
<p><img src="https://i.imgur.com/yVwqduQ.png" />
<br /></p>
<p>Curating your own library (and its “shelves”) is not as easy as one might think. In addition to the fact that my shelves are patently absurd (see <a href="https://www.goodreads.com/review/list/1923002?shelf=codename-duchess"><strong>Codename Duchess</strong></a> for my Archer-related reviews, and or <a href="https://www.goodreads.com/review/list/1923002-mara?shelf=baby-shower-gift-guide"><strong>Baby Shower Gift Guide</strong></a> for books I think would make good baby shower gifts— y’know, ones like <a href="https://www.goodreads.com/review/show/723069879?book_show_action=false&amp;from_review_page=1">The Boys from Brazil</a>, and <a href="https://www.goodreads.com/review/show/846607689?book_show_action=false&amp;from_review_page=1">The Midwich Cuckoos</a>) I don’t always know ahead of time that I will end up reading a shelf-worthy number of books about a given topic until after the fact.</p>
</div>
</div>
<div id="ok-now-we-can-rvest" class="section level3">
<h3>OK, <em>now</em> we can <code>rvest</code></h3>
<p>The code should be pretty self-explanatory. If you want to do this for your own books, you’d just switch out the <code>startURL</code> so that it points to <em>your</em> shelves, as opposed to mine.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p>
<pre class="r"><code>library(tidyverse)
library(stringr)
library(rvest)

startUrl &lt;- &quot;https://www.goodreads.com/review/list/1923002-mara&quot;


# function to get book descriptions
getBookDescription &lt;- function(bookLink) {
  url &lt;- str_c(&quot;https://www.goodreads.com&quot;, bookLink)
  read_html(url) %&gt;%
    html_node(&quot;#descriptionContainer&quot;) %&gt;%
    html_text() %&gt;%
    trimws()
}

# function to get book genres
get_genres &lt;- function(bookLink){
  url &lt;- str_c(&quot;https://www.goodreads.com&quot;, bookLink)
  read_html(url) %&gt;%
    html_nodes(&quot;.left .bookPageGenreLink&quot;) %&gt;%
    html_text(trim = TRUE)
}

# function to get books
getBooks &lt;- function(i) {
  cat(i, &quot;\n&quot;)
  url &lt;- str_c(startUrl, &quot;?page=&quot;, i, &quot;&amp;shelf=read&quot;)

  html &lt;- read_html(url)

  title &lt;- html %&gt;%
    html_nodes(&quot;.title a&quot;) %&gt;%
    html_text(trim = TRUE) #%&gt;%
  #discard(!str_detect(., &quot;[A-Z0-9]&quot;))

  author &lt;- html %&gt;%
    html_nodes(&quot;.author a&quot;) %&gt;%
    html_text(trim = TRUE) %&gt;%
    discard(str_detect(., &quot;^\\(&quot;))

  bookLinks &lt;- html %&gt;%
    html_nodes(&quot;a&quot;) %&gt;%
    html_attr(&quot;href&quot;) %&gt;%
    discard(!str_detect(., &quot;^/book/show&quot;)) %&gt;%
    na.omit() %&gt;%
    unique()

  bookDescription &lt;- bookLinks %&gt;%
    map_chr(getBookDescription)

  bookGenre &lt;- bookLinks %&gt;%
    map(get_genres)

  return(tibble(
    title = title,
    author = author,
    book_description = bookDescription,
    book_genres = bookGenre
  ))
}

# get books (30 per page, 1266 books -&gt; 43 pages)
goodreads &lt;- c(1:43) %&gt;%
  map_dfr(getBooks)

# save the output
write_csv(goodreads, path = here(&quot;output&quot;, &quot;goodreads_read.csv&quot;))</code></pre>
</div>
</div>
<div id="exploring-books-ive-read" class="section level2">
<h2>Exploring books I’ve read</h2>
<div id="cleaning-descriptions" class="section level3">
<h3>Cleaning descriptions</h3>
<pre class="r"><code>clean_book_descs &lt;- read_books_data %&gt;%
  mutate(clean_desc = str_replace_all(book_description, &quot;[^a-zA-Z\\s]&quot;, &quot; &quot;)) %&gt;%
  mutate(clean_desc = str_trim(clean_desc, side = &quot;both&quot;)) %&gt;%
  select(-book_genres)</code></pre>
</div>
</div>
<div id="tidytext-time" class="section level2">
<h2><code>tidytext</code> time</h2>
<p>Now it’s time to use the excellent <a href="https://github.com/juliasilge/tidytext"><code>tidytext</code></a> 📦 by Julia Silge and David Robinson (which you can learn all about in their book, <a href="http://tidytextmining.com/">Text Mining with R</a>) to explore what’s in these descriptions.</p>
<div id="unnest_tokens" class="section level4">
<h4><code>unnest_tokens</code></h4>
<p>The descriptions we’ve cleaned will be <strong>unnested</strong> into individual tokens (in this case, words), and we can get rid of the pre-cleaning book descriptions for now (especially since we still have <code>book_id</code>s at the ready, should we want to get more info aout a particular book).</p>
<pre class="r"><code>library(tidytext)

descs_unnested &lt;- clean_book_descs %&gt;%
  unnest_tokens(word, clean_desc) %&gt;%
  select(-book_description)</code></pre>
<p>Let’s also take a look at the word stems using the <code>SnowballC</code> package.</p>
<pre class="r"><code>library(SnowballC)

descs_unnested &lt;- descs_unnested %&gt;%
  mutate(word_stem = wordStem(word, language=&quot;english&quot;))</code></pre>
</div>
<div id="stop_words" class="section level4">
<h4><code>stop_words</code> ✌🏿</h4>
<p>Now we’ll get rid of stop words (using the dataset built into <code>tidytext</code>), and count word frequencies.</p>
<pre class="r"><code>data(&quot;stop_words&quot;)

tidy_books &lt;- descs_unnested %&gt;%
  anti_join(stop_words, by = &quot;word&quot;)

tidy_book_words &lt;- tidy_books %&gt;%
  count(word, sort = TRUE)

tidy_book_words</code></pre>
<pre><code>## # A tibble: 21,172 x 2
##    word         n
##    &lt;chr&gt;    &lt;int&gt;
##  1 world      981
##  2 story      767
##  3 life       765
##  4 book       666
##  5 history    499
##  6 time       479
##  7 war        454
##  8 people     429
##  9 author     406
## 10 american   404
## # ... with 21,162 more rows</code></pre>
<p>The top words make sense. I <em>do</em> read a lot of books about life, stories, the world, history, time, and people. The book descriptions often begin with editorial praise, e.g.</p>
<blockquote>
<p><em>From the New York Times best-selling author of…</em></p>
</blockquote>
<p>So, it’s not surprising that words like “book” and “author” would make it into the top ten, as well.</p>
<p>We could also look at these aggregates by word <em>stem</em>.</p>
<pre class="r"><code>tidy_book_word_stems &lt;- tidy_books %&gt;%
  count(word_stem, sort = TRUE)

tidy_book_word_stems</code></pre>
<pre><code>## # A tibble: 14,319 x 2
##    word_stem     n
##    &lt;chr&gt;     &lt;int&gt;
##  1 world      1001
##  2 stori       967
##  3 time        860
##  4 book        815
##  5 life        767
##  6 histori     509
##  7 author      495
##  8 war         488
##  9 american    486
## 10 live        475
## # ... with 14,309 more rows</code></pre>
<p>Though the word stems themselves are not easy to read, we’ve reduced the number of unique words by grouping together words with the same stem. There are 21172 unique words, and 14319 unique word stems. The counts for word stems are higher than for words, since multiple words have the same stems, e.g. world and worlds, story and stories, etc.</p>
</div>
<div id="get_sentiments-with-afinn" class="section level4">
<h4><code>get_sentiments</code> 😼 😠 😭 with AFINN</h4>
<p>I won’t go into the details here (for those, check out the <a href="http://tidytextmining.com/sentiment.html">Sentiment analysis with tidy data</a> section of Julia and David’s book), but let’s take a look at the sentiments associated with the words from my read book descriptions. I’ll use the <code>AFINN</code> lexicon, which:</p>
<blockquote>
<p>“…assigns words with a score that runs between -5 and 5, with negative scores indicating negative sentiment and positive scores indicating positive sentiment” (Silge &amp; Robinson 2017, p.14)</p>
</blockquote>
<p>It is important to note, however, that this is a very much a subset of the words used in the book descriptions, and that the “censored” data may have a disproportionate impact in one direction or another.</p>
<pre class="r"><code>data(sentiments)

word_sentiments &lt;- tidy_book_words %&gt;%
  inner_join(get_sentiments(&quot;afinn&quot;), by = &quot;word&quot;)

word_sentiments</code></pre>
<pre><code>## # A tibble: 1,513 x 3
##    word         n score
##    &lt;chr&gt;    &lt;int&gt; &lt;int&gt;
##  1 war        454    -2
##  2 love       298     3
##  3 murder     234    -2
##  4 crime      221    -3
##  5 death      216    -2
##  6 true       202     2
##  7 powerful   181     2
##  8 dead       163    -3
##  9 winning    153     4
## 10 award      151     3
## # ... with 1,503 more rows</code></pre>
<p>I was a little surprised when I first saw some of these. For <code>kill</code> and <code>crime</code>, the AFINN score is -3, but <code>murder</code> is only a -2. The word <code>winning</code> merits a positive 4, but <code>war</code> only gets a negative 2!</p>
<p>You can learn more about AFINN <a href="http://www2.imm.dtu.dk/pubdb/views/publication_details.php?id=6010">here</a>, and I’m not knocking it. It’s not like <em>I’ve</em> gone through 2,476 words and phrases and rated them for valence! However, it’s always good to look at your data and see what’s going on.</p>
<p>In fact, let’s take a look at all of the AFINN sentiment scores from the sentiments dataset.</p>
<pre class="r"><code>library(hrbrthemes)  # because I like pretty things

sentiments %&gt;%
  filter(!is.na(score)) %&gt;%
  group_by(score) %&gt;%
  ggplot(aes(score)) +
  geom_bar() +
  labs(title = &quot;AFINN sentiment score distribution&quot;,
       xlab = &quot;AFINN score&quot;,
       ylab = &quot;count&quot;) +
  theme_ipsum_rc()</code></pre>
<p><img src="../../../post/2017-10-17-goodreads-part-2_files/figure-html/afinn_sentiments-1.png" width="700" /></p>
<p>So, yeah, looks like there’s a whole lot of -2 going on. That’s not to say it’s incorrect— just worth noting out of curiosity.</p>
<p>Now let’s take a quick gander at the distribution of AFINN scores in the words that appeared both in the descriptions of the books I read, and in the AFINN lexicon. To be fair, we’re not really comparing 🍏s to 🍎s here. The AFINN Lexicon says nothing with respect to the frequency of the words it scores.</p>
<pre class="r"><code>word_sentiments %&gt;%
  group_by(score) %&gt;%
  summarise(score_tot = sum(n)) %&gt;%
  ggplot(aes(x = score, y = score_tot)) +
  geom_bar(stat = &quot;identity&quot;) +
  labs(title = &quot;Book-description word sentiment distribution&quot;,
       x = &quot;AFINN score&quot;,
       y = &quot;count total&quot;,
       caption = &quot;Source: Mara&#39;s Goodreads export 2017-10-12&quot;) +
  theme_ipsum_rc()</code></pre>
<p><img src="../../../post/2017-10-17-goodreads-part-2_files/figure-html/desc_word_afinn_dist-1.png" width="700" /></p>
</div>
</div>
<div id="take-a-breather" class="section level2">
<h2>Take a breather! 😤</h2>
<p>There’s much more to be unpacked, but I’m told that human attention spans aren’t what they used to be. So, until next time 🌊</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p><em>Spoiler alert:</em> It really wasn’t.<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>If you actually want to learn more about it, check out the aforementioned <a href="https://cran.r-project.org/web/packages/rvest/vignettes/selectorgadget.html">SelectorGadget vignette</a>, and/or a series of great tutorials from UseR2016 <a href="https://github.com/ropensci/user2016-tutorial">Extracting data from the web APIs and beyond</a> by Karthik Ram, Garrett Grolemund and Scott Chamberlain, if you want a more thorough R/webscraping education.<a href="#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>There are some good answers about this on Stack Overflow using <a href="https://stackoverflow.com/a/38760066/785190">rvest</a> alone, or with other packages such as <a href="https://stackoverflow.com/a/40275000/785190">RSelenium</a>.<a href="#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p>Sorry, this doesn’t exactly match up with the read books in this and/or my previous Goodreads post, as I’ve finished a few more between when I first started writing this and now. 😜<a href="#fnref4" class="footnote-back">↩</a></p></li>
<li id="fn5"><p>Because this process take a while, the code here is shown (<code>echo = TRUE</code>, if you’re familiar with R Markdown chunks), but not actually run (<code>eval = FALSE</code> in Rmd terms).<a href="#fnref5" class="footnote-back">↩</a></p></li>
</ol>
</div>

        </div>
        <footer class="article-footer">
    <a data-url="/2017/10/goodreads-part-2/" data-id="d8c781643b413faae3054f41f539f48f" text="Goodreads 👍📚 Part 2: rvesting descriptions" via="acastillogill" class="article-share-link">
        <i class="fas fa-share"></i>
        Share
    </a>
    
    <a href="../../../2017/10/goodreads-part-2/#disqus_thread" class="article-comment-link">
        Comments
    </a>
    

    <script>
    (function ($) {
        
        if (typeof(__SHARE_BUTTON_BINDED__) === 'undefined' || !__SHARE_BUTTON_BINDED__) {
            __SHARE_BUTTON_BINDED__ = true;
        } else {
            return;
        }
        $('body').on('click', function() {
            $('.article-share-box.on').removeClass('on');
        }).on('click', '.article-share-link', function(e) {
            e.stopPropagation();

            var $this = $(this),
                url = $this.attr('data-url'),
                encodedUrl = encodeURIComponent(url),
                titleText = $this.attr('text'),
                via = $this.attr('via'),
                id = 'article-share-box-' + $this.attr('data-id'),
                offset = $this.offset(),
                box;

            if ($('#' + id).length) {
                box = $('#' + id);

                if (box.hasClass('on')){
                    box.removeClass('on');
                    return;
                }
            } else {
                var html = [
                    '<div id="' + id + '" class="article-share-box">',
                        '<input class="article-share-input" value="' + url + '">',
                        '<div class="article-share-links">',
                            '<a href="https://twitter.com/share?url=' + encodedUrl + '&text=' + titleText + '&via=' + via + '" class="fab fa-twitter article-share-twitter" target="_blank" title="Twitter"></a>',
                            '<a href="https://www.facebook.com/sharer.php?u=' + encodedUrl + '" class="fab fa-facebook article-share-facebook" target="_blank" title="Facebook"></a>',
                            '<a href="http://pinterest.com/pin/create/button/?url=' + encodedUrl + '" class="fab fa-pinterest-p article-share-pinterest" target="_blank" title="Pinterest"></a>',
                            '<a href="https://plus.google.com/share?url=' + encodedUrl + '" class="fab fa-google article-share-google" target="_blank" title="Google+"></a>',
                        '</div>',
                    '</div>'
                ].join('');

              box = $(html);

              $('body').append(box);
            }

            $('.article-share-box.on').hide();

            box.css({
                top: offset.top + 25,
                left: offset.left
            }).addClass('on');

        }).on('click', '.article-share-box', function (e) {
            e.stopPropagation();
        }).on('click', '.article-share-box-input', function () {
            $(this).select();
        }).on('click', '.article-share-box-link', function (e) {
            e.preventDefault();
            e.stopPropagation();

            window.open(this.href, 'article-share-box-window-' + Date.now(), 'width=500,height=450');
        });
    })(jQuery);
    </script>
</footer>

    </div>

    
<nav id="article-nav">
    
    <a href="../../../2017/10/mousey-methods/" id="article-nav-older" class="article-nav-link-wrap">
      <strong class="article-nav-caption">
          Older
      </strong>
      <div class="article-nav-title">🙈 mousey methods</div>
    </a>
    

    
    <a href="../../../2017/10/updating-blogdown-hugo-version-netlify/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">
          Newer
      </strong>
      <div class="article-nav-title">Updating your version of Hugo for blogdown on Netlify</div>
    </a>
    
</nav>


</article>


<section id="comments">
    <div id="disqus_thread">
        <div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "https-acastillogill-com" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>
</section>


    </section>

   	
    	<aside id="sidebar">
    

    

    

    


    <div id="toTop" class="fa fa-angle-up"></div>
</aside>

    
	</div>
</div>

<footer id="footer">
  <div class="outer">
    <div id="footer-info" class="inner">
      &copy; 2018
      Ángela Castillo-Gill. Powered by <a href="//gohugo.io">Hugo</a>. Theme by <a href="https://github.com/ppoffice">PPOffice</a>. Customised by <a href="https://github.com/ppoffice">Mara Averick</a>
    </div>
  </div>
</footer>


<script type="application/javascript">
var dnt = (navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack);
var doNotTrack = (dnt == "1" || dnt == "yes");
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	if (window.sessionStorage) {
		var GA_SESSION_STORAGE_KEY = 'ga:clientId';
		ga('create', 'UA-128602464-1', {
	    'storage': 'none',
	    'clientId': sessionStorage.getItem(GA_SESSION_STORAGE_KEY)
	   });
	   ga(function(tracker) {
	    sessionStorage.setItem(GA_SESSION_STORAGE_KEY, tracker.get('clientId'));
	   });
   }
	
	ga('send', 'pageview');
}
</script>

<script src="../../../fancybox/jquery.fancybox.pack.js"></script>
<script src="../../../js/script.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>


<script>hljs.initHighlightingOnLoad();</script>


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']]}
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>




</body>
</html>