---
title: Communicating science
author: Ángela Castillo-Gill
date: '2018-11-08'
slug: communicating-science
categories:
  - Journal
tags: 
  - Prioritising
  - Learning
draft: FALSE
summary: Prioritising tips 
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 2
  fig_caption: true
editor_options: 
  chunk_output_type: console
---

Today I am at a science communication workshop. This is what my story would be like. 

**Title:** So, you want to make your property more valuable. What factors actually make a difference. 

**Short description:** After processing 2000 + observations from the IDEALISTA database to really reveal what contributes to property prices, I will reveal whether or not forestry in your backyard make a difference to your property prices. And if it does, what kind of trees make a difference?

**Exhaustive description:** A cost-benefit analysis on a conservation policy to preserve palm trees in Catalonia shows negative results. Benefits derived from the conservation of palm trees pale in comparison to the policy's costs. 

Should the public spend that much from their taxes preserve trees that aren't generating that much economic value? Taxpayers, palm trees, property owners in Europe all have a say. The benefits were studied in Catalonia but can potentially be extended to the rest of Europe where the policy is in place. The policy came into place in 2007 till now. 

By estimating the number of palm trees in Catalonia and then quantifying their benefits in contrast to the associated benefits. 
