---
title: "Structure"
subtitle: "Today it's all about planning how to write up the final blogpost."
author: Ángela Castillo-Gill
date: '2018-11-23'
slug: structure
categories:
  - Journal
tags: 
  - Learning
draft: FALSE
summary: "Today it's all about planning how to write up the final blogpost."
output:
 blogdown::html_page:
  fig_caption: true
editor_options: 
  chunk_output_type: console
---

# Daily goals:

1. Plan the structure of the final blogpost.

## Goal 1: Plan the structure of the final blogpost.

```{r read data, echo=FALSE, message=FALSE}
library(tidyverse)
library(rpart)
library(rpart.plot)
library(knitr)
options(digits=4)
options(scipen = 999)
opts_chunk$set(echo = FALSE,
               warning = FALSE,
               error = FALSE,
               message = FALSE,
               collapse= TRUE,
               comment = NA,
               tidy = TRUE)
theme_set(theme_light())
homes <- readRDS(file="/Volumes/TOSHIBAEXT/google_drive/acastillogill/content/homes.rds")
homes <- homes%>%
  select(-Id)
```

This is the second blogpost I'm going to be publishing. I want to set out a plan and know well what I'm going to include and what I'm not going to include. 

The first step is to remind myself why I'm publishing this blog post. The reason is...

**drumroll**

I want to show how I applied the regression tree algorithm to a Kaggle dataset.

If that is my goal, then let's answer the other four W's and one H in function of that. 

Where: On this very site and also as a kernel on Kaggle.
When: Sometime next week.
Who's the reader: Interested people in the regression tree algorithm, Kaggle users and learners
What: I want to do a short but informative blogpost. Where I explain a problem and the solution I propose. 

How: By being very concise about what is the final goal of the post and what is the roadmap to get there.

So that's like my meta intention for the blogpost, now in detail I think it would go something like:

1. Business question: Let's say that you have a house in Ames, Iowa (that's where the dataset is from). Let's say you are about to buy a house or even buy some terrain and you want to understand what makes a house more valuable than an other one.

A quite cool business question that I don't know if I'll be able to answer but we'll see is: are there any features that can be added to the house that can significantly increase it's value. A good idea would be to buy a house for a low value with features that are modifiable (i.e. kitchen, exterior, etc.), modify those features and resell that house. 

It's a naive idea since probably the potential to do that is already reflected in the prices. 

So I would state to be the goal, then I would say, here is how I'm going to solve that problem, I'm going to understand the dataset, how it was collected, what are the key features, and then, I'm going to motivate the use of one algorithm over another. Like what's so special about regression trees that I'm going to use it. 

Then I'm going to use it and explain the outcome. I want to give a lot of attention to the interpretability since this is a particular advantage of regression trees and prime reason for selecting it. 

There was some important work in terms of data cleaning. I want to give this some attention but not so much that the post becomes about data cleaning. 

OK. So I think that's a solid plan:

1. Business question
2. Dataset description 
3. Motivation for tool
4. Steps 
5. Result
6. Interpretation

Oh! Another think I forgot, I do have a nagging question about whether I should partition my data or not with rpart. Somewhere I think I read that cross-validation was built into rpart so I shouldn't split my data. But then the DataCamp course I did said I should... One for CrossValidated I think.