---
title: Spanish trade over time
author: Ángela D. Castillo-Gill
date: '2018-09-24'
slug: spanish-trade-over-time
categories:
  - R
  - EDA
tags: 
  - Kaggle
  - Kiva
summary: What and from where does Spain import?
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 2
  fig_caption: true
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
x <-
  c("tidyverse",
    "knitr",
    "formatR",
    "stringr",
    "lubridate",
    "tidyr",
    "formattable",
    "grid",
    "gridExtra",
    "kableExtra",
    "xts",
    "timetk")

lapply(x, require, character.only = TRUE)


opts_chunk$set(echo = FALSE,
               warning = FALSE,
               error = FALSE,
               message = FALSE,
               collapse= TRUE,
               comment = NA,
               tidy = TRUE)
```

# Summary




# Purpose of this post



# The data

```{r}
# Read trade data
trade <- read_csv("/Volumes/TOSHIBAEXT/google_drive/PhD/Database/commodity_trade_statistics_data.csv")
```

```{r}
#Filter imports for Spain and Portugal and save in ib_trade
trade %>%
  filter(country_or_area=="Spain",
         flow=="Import") -> trade_Spain

trade %>%
  filter(country_or_area=="Portugal",
         flow=="Import") -> trade_Portugal
```

```{r}
#Make year a date
trade_Spain$year <- as.Date(paste(trade_Spain$year,
                                     12, 31, sep = "-"))
#Make the commodity variable a factor
trade_Spain$commodity <- as.factor(trade_Spain$commodity)
#Make categories a factor
trade_Spain$category <- as.factor(trade_Spain$category)
```

```{r}
#Filter imports for liveanimals and save in ib_trade_liveanimals
spain_01<-trade_Spain %>%
  filter(category=="01_live_animals") #animals
```

```{r}
#Make ib_trade_liveanimals an xts object
ib_trade_xts_animals <- tk_xts(spain_01, date_var=year)
```

```{r}

```

